---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dt1098-#{env}#-hpa-memory
  namespace: #{namespace}#
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dt1098
  minReplicas: #{dh-k1-min-replicas}#
  maxReplicas: #{dh-k1-max-replicas}#
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: #{dh-k1-memory-utilisation}#