---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: #{projectname}#
  namespace: #{namespace}#
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      label: #{projectname}#
  template:
    metadata:
      labels:
        label: #{projectname}#
    spec:
      securityContext:
        runAsUser: 1221
      volumes:
        - name: azurefileshare
          azureFile:
            secretName: storage-secret-input
            shareName: input-dir
        - name: azurefileshare1
          azureFile:
            secretName: storage-secret-output
            shareName: output-dir
        - name: azurefileshare2
          azureFile:
            secretName: storage-secret-output
            shareName: classification-model
      containers:
        - name: #{projectname}#
          image: #{containerregistry}#.azurecr.io/#{k1repository}#:#{Build.BuildId}#
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            requests:
              cpu: #{dh-k1-cpu}#
              memory: #{dh-k1-memory}#
          volumeMounts:
            - name: azurefileshare
              mountPath: /input-dir
            - name: azurefileshare1
              mountPath: /output-dir
            - name: azurefileshare2
              mountPath: /classification-model
          
      imagePullSecrets:
          - name: #{acr-secrets}#